name: Run Pix Bot Daily

on:
  schedule:
    - cron: "0 20 * * *"  # 20:00 UTC = 17:00 em Brasília (America/Sao_Paulo)
  workflow_dispatch:

permissions:
  contents: write

# Evita duas execuções em paralelo se uma demorar >5min
concurrency:
  group: pix-bot
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTIONS: "true"
      OUT_DIR: "."
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: |
          echo "Trigger: ${{ github.event_name }} at $(date -u) UTC"
          python bot.py
          # Para intervalo específico:
          # python bot.py 202501 202508

      - name: Upload Excel as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pix_pordia_xlsx
          path: pix_pordia.xlsx
          if-no-files-found: warn

      - name: Commit updated Excel back to repo
        run: |
          set -e
          if [ -f "pix_pordia.xlsx" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add pix_pordia.xlsx
            if git diff --cached --quiet; then
              echo "Nenhuma mudança no Excel. Nada a commitar."
            else
              git commit -m "Update pix_pordia.xlsx [skip ci]"
              git push
            fi
          else
            echo "Arquivo pix_pordia.xlsx não encontrado para commit."
          fi
